spring:
  application:
    name: message-service
  data:
    mongodb:
      uri: ${MONGO_URI}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:     ${JWT_SECRET}
  expiration: 3600000

server:
  port: ${PORT:5600}
  servlet:
    context-path: /api

supabase:
  url:    ${SUPABASE_URL}
  bucket: ${SUPABASE_BUCKET}
  key:    ${SUPABASE_KEY}