server:
  port: 5600
  servlet:
    context-path: /api

spring:
  application:
    name: message-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/mydatabase?authSource=admin

jwt:
  secret: myUltraSuperSecretKeyThatIsAtLeast32Chars!
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG