spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}
  expiration: 18000000

server:
  port: ${PORT:5500}
  servlet:
    context-path: /api/users

supabase:
  url: ${SUPABASE_URL}
  bucket: ${SUPABASE_BUCKET}
  key: ${SUPABASE_KEY}