
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/xchat_users
    username: admin
    password: weblinedb
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: myUltraSuperSecretKeyThatIsAtLeast32Chars!
  expiration: 18000000

server:
  port: 5500
  servlet:
    context-path: /api/users

supabase:
  url: https://xkhlsiuhegxveuxciceh.supabase.co
  bucket: profile_pic
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhraGxzaXVoZWd4dmV1eGNpY2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3OTgxNjYsImV4cCI6MjA5NTM3NDE2Nn0.wG5P0stFov0hNIxpHpsOAYJGNln9Phum3WXAXYdsUaw

app:
  api:
    user: /user
    auth: /auth
    signup: /signup
    login: /login
    by-id: /{id}
    search: /search
    friend: /friend
    addfriend: /add
    acceptfriend: /accept/{id}
    cancelrequest: /cancel/{id}
